import { Injectable } from '@nestjs/common';
import { MailerService } from '@nestjs-modules/mailer';

@Injectable()
export class EmailService {
  constructor(private readonly mailerService: MailerService) {}

  /**
   * Sends the password reset email to the specified email address with the provided reset URL.
   * 
   * @param toEmail - The email address of the user requesting a password reset.
   * @param resetUrl - The URL that the user can click to reset their password. This URL should be generated by the backend and typically includes a secure token.
   */
  async sendPasswordResetEmail(toEmail: string, resetUrl: string) {
    try {
      await this.mailerService.sendMail({
        to: toEmail,
        subject: '🔒 Password reset for KeepTrack application',
        // Simple HTML. You can connect Pug/EJS templates here in the future!
        html: `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <h2 style="color: #2563eb;">Reset Forgotten Password</h2>
            <p>Hi,</p>
            <p>We received a request to reset the password for your KeepTrack account.</p>
            <p>If you did not request this change, you can safely ignore this email. Your password will remain unchanged.</p>
            <div style="margin: 30px 0;">
              <a href="${resetUrl}" style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold;">
                Set New Password
              </a>
            </div>
            <p style="color: #64748b; font-size: 14px;">
              Or copy this link into your browser:<br>
              <a href="${resetUrl}" style="color: #2563eb; word-break: break-all;">${resetUrl}</a>
            </p>
            <p style="color: #64748b; font-size: 14px; margin-top: 40px;">
              For security reasons, this link will expire in 1 hour.
            </p>
          </div>
        `,
      });
      console.log(`Password reset email sent to: ${toEmail}`);
    } catch (error) {
      console.error('Error sending email via Brevo:', error);
      // You can throw the error or log it and let the backend keep running
      throw error;
    }
  }

  /**
   * Sends a feedback email to the specified recipient with the provided subject and message. The email content is sanitized to prevent HTML injection.
   * 
   * @param to - The email address of the recipient who will receive the feedback.
   * @param subject - The subject line of the feedback email, which should summarize the feedback being sent.
   * @param message - The body of the feedback email, containing the detailed feedback message. This content will be sanitized to prevent any HTML injection.
   */
  async sendFeedbackEmail(to: string, subject: string, message: string) {
    try {
      const escapeHtml = (str: string) =>
        str
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;')
          .replace(/'/g, '&#039;');

      const safeSubject = escapeHtml(subject);
      const safeMessage = escapeHtml(message);

      await this.mailerService.sendMail({
        to: to,
        subject: subject,
        html: `<div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                <h2 style="color: #2563eb;">New Feedback Received</h2>
                <p>${safeSubject}</p>
                <p>${safeMessage}</p>
              </div>`,
      });
    } catch (error) {
      console.error('Error sending feedback email:', error);
      throw error;
    }
  }
}
