services:
  postgres:
    image: postgres:15-alpine
    container_name: keeptrack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: keep-track
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: keeptrack-api
    environment:
      # URL musí přesně sedět na jméno kontejneru (postgres), port 5432 a heslo výše
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      BREVO_SMTP_USER: ${BREVO_SMTP_USER}
      BREVO_SMTP_PASSWORD: ${BREVO_SMTP_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL} 
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: keeptrack-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
