server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Zajišťuje správné fungování Single Page Application (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Nepovinné: Kešování statických souborů pro větší rychlost
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}